
# Netlify configuration file

# The following redirect rule tells Netlify to route all requests to index.html
# This allows client-side routing to work correctly with React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Optimize build settings
[build]
  publish = "dist"
  command = "vite build"

# Handle SPA routing
[dev]
  framework = "vite"
